LockableBlocks:
  CHEST: true
  BREWING_STAND: true
  FURNACE: true
  DISPENSER: true
  JUKEBOX: true
  WOODEN_DOOR: true
  TRAP_DOOR: true
  FENCE_GATE: true
  WOODEN_BUTTON: true
  STONE_BUTTON: true
  WOOD_PLATE: true
  STONE_PLATE: true
  LEVER: true
  ENDER_CHEST: true